spring:
  application:
    name: student-management-api
  datasource:
    url: jdbc:h2:file:./data/schooldb;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none # I have my own schema.sql and data.sql files
    defer-datasource-initialization: true
  sql:
    init:
      mode: always  # Runs schema.sql then data.sql each boot
      continue-on-error: false

logging:
  level:
    org.hibernate.SQL: warn

springdoc:
  swagger-ui:
    path: /docs
    display-request-duration: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    docExpansion: none
    syntaxHighlight:
      activated: true
    persistAuthorization: true